bind ="127.0.0.1"
port = 8545

[servers]

  [servers.alpha]
  ip = "127.0.0.1"
  port = "8181"
  weight = 5

  [servers.beta]
  ip = "127.0.0.1"
  port = "8080"

  [servers.gamma]
  ip = "127.0.0.1"
  port = "8282"
  backup = true