bind ="127.0.0.1"
port = 8545

[[servers]]
ip = "127.0.0.1"
port = "8181"
weight = 5
token = "aaaaaa"

[[servers]]
ip = "127.0.0.1"
port = "8080"
token = "11123433242341"

[[servers]]
ip = "127.0.0.1"
port = "8282"
token = "weuyroiwuqyr"
