bind ="0.0.0.0"
port = "8545"
adminport = "8080"

websocket = "ws://127.0.0.1:8080/ws"  #поменять на реальный айпи доступный с инета или сети где нужно смотреть статистику порт брать тот же который в adminport

socketpath = "/tmp/gethinx.sock"

suspend = 30 # время в секундах  за которое должен обновится бекенд прежде чем считатся не активным
ticker  = 10 # время через которое будет опрашиватся каждый сервер на предмет нового блока
maxresponsetime = 30 # время секундах  через которое сервер не будет участвовать в получении новых запросов, кроме запросов на последний блок
key      = "7f81c777667e559204b2794a846976b39cfe8248c5f62da5aa977926d8a42349"

[slack]
use = true
token = "xoxb-678678678-JHITYUYFJHJFUSSPEK"
channel = "C97988998789" #global

[telegram]
use = true
token ="kjhlkhlhlkhlkh"


[[servers]]
hostname = "node02.versus.dev"
ip = "127.0.0.1"
port = "8181"
token = "XDZSCFVGBH"

[[servers]]
hostname = "node03.versus.dev"
ip = "127.0.0.1"
port = "8282"
token = "weuyroiwuqyr"

