bind ="10.55.24.68"
port = "8545"
adminport = "8080"

socketpath = "/tmp/gethinx.sock"

suspend = 30 # время в секундах  за которое должен обновится бекенд прежде чем считатся не активным
key      = "7f81c777667e559204b2794a846976b39cfe8248c5f62da5aa977926d8a42349"

[slack]
use = true
token = "xoxb-678678678-JHITYUYFJHJFUSSPEK"
channel = "C97988998789" #global

[telegram]
use = true
token ="kjhlkhlhlkhlkh"

[[servers]]
hostname = "node01.versus.dev"
ip = "10.55.24.247"
port = "8282"
weight = 5
token = "Q!@W#E$R%T^Y"

[[servers]]
hostname = "node02.versus.dev"
ip = "127.0.0.1"
port = "8080"
token = "XDZSCFVGBH"

[[servers]]
hostname = "node03.versus.dev"
ip = "127.0.0.1"
port = "8282"
token = "weuyroiwuqyr"

